name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Make the production plugin bundle
        run: |
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          yarn
          yarn build

          # --- FIX: STEP 1 - CREATE THE PACKAGE ---
          # 'npm pack' creates the .tar.gz file in the root directory.
          npm pack

          # --- FIX: STEP 2 - MOVE THE PACKAGE TO THE DIST FOLDER ---
          # The release action looks for the file in 'dist/', so we move it there.
          # The wildcard '*' ensures this works for any version number.
          mv *.tar.gz dist/

      - name: Perform Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: |
            dist/*.tar.gz