name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build and Package Plugin
        id: package-step # Give the step an ID
        run: |
          # Install dependencies and build the JS file
          yarn
          yarn build

          # --- This is the correct way to create the package ---
          # 'npm pack' creates the .tar.gz file in the root directory
          PACKAGE_FILENAME=$(npm pack)

          # Move the package to the dist folder for the release step
          mv "$PACKAGE_FILENAME" dist/

          # Save the filename for the next step
          echo "::set-output name=asset_name::$PACKAGE_FILENAME"

      - name: Perform Github Release
        uses: softprops/action-gh-release@v1
        with:
          # Get the version directly from the package.json file
          tag_name: v${{ fromJson(readFile('package.json')).version }}
          generate_release_notes: true
          # Use the output from the previous step to find the file
          files: dist/${{ steps.package-step.outputs.asset_name }}