name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build and Package Plugin
        id: package-step
        run: |
          # --- This is the correct way to get the version ---
          # It reads the version from package.json and saves it as an environment variable
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV

          # Install dependencies and build the JS file
          yarn
          yarn build

          # Create the compressed .tar.gz package
          PACKAGE_FILENAME=$(npm pack)

          # Move the package to the dist folder for the release step
          mv "$PACKAGE_FILENAME" dist/

          # Save the final package filename for the next step
          echo "::set-output name=asset_name::$PACKAGE_FILENAME"

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          # --- This is the correct way to use the version ---
          # It now reads from the environment variable set in the previous step
          name: Release v${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          # This points to the final asset file
          files: dist/${{ steps.package-step.outputs.asset_name }}